// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzKfJdphy-8wuKYuXBfSdteLHF6vEk8SU',
    appId: '1:934375161853:web:2eba6085146710e0bde394',
    messagingSenderId: '934375161853',
    projectId: 'dummy-84654',
    authDomain: 'dummy-84654.firebaseapp.com',
    storageBucket: 'dummy-84654.appspot.com',
    measurementId: 'G-B0KDW758S5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpIaXwHFJ7hUPxCSIhEAwss8e7_nmcpKI',
    appId: '1:934375161853:android:bf088bb1aa22ea8ebde394',
    messagingSenderId: '934375161853',
    projectId: 'dummy-84654',
    storageBucket: 'dummy-84654.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkA5hQ7mb_kTWWyAsrURNx1zRh2waKLQc',
    appId: '1:934375161853:ios:8dd4ff35035d741abde394',
    messagingSenderId: '934375161853',
    projectId: 'dummy-84654',
    storageBucket: 'dummy-84654.appspot.com',
    iosClientId: '934375161853-p27ulkf439nuacud9c75egn2tqoguqml.apps.googleusercontent.com',
    iosBundleId: 'com.example.trial1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkA5hQ7mb_kTWWyAsrURNx1zRh2waKLQc',
    appId: '1:934375161853:ios:8dd4ff35035d741abde394',
    messagingSenderId: '934375161853',
    projectId: 'dummy-84654',
    storageBucket: 'dummy-84654.appspot.com',
    iosClientId: '934375161853-p27ulkf439nuacud9c75egn2tqoguqml.apps.googleusercontent.com',
    iosBundleId: 'com.example.trial1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzKfJdphy-8wuKYuXBfSdteLHF6vEk8SU',
    appId: '1:934375161853:web:4baa34990cf2e6aabde394',
    messagingSenderId: '934375161853',
    projectId: 'dummy-84654',
    authDomain: 'dummy-84654.firebaseapp.com',
    storageBucket: 'dummy-84654.appspot.com',
    measurementId: 'G-E8C6P4NP9W',
  );

}